### ISSUE TITLE
Errors spam, maybe crash

### ISSUE THREAD

**Issue by sanyashvets** [dries007/HoloInventory#14]
```
java.lang.NullPointerException
at net.dries007.holoInventory.util.InventoryData.(InventoryData.java:48)
at net.dries007.holoInventory.server.ServerEventHandler.doStuff(ServerEventHandler.java:226)
at net.dries007.holoInventory.server.ServerEventHandler.event(ServerEventHandler.java:156)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_139_ServerEventHandler_event_PlayerTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:355)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:380)
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:393)
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:482)
at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36)
at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(C03PacketPlayer.java:182)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
at java.lang.Thread.run(Thread.java:745)
```

Have no idea what exactly block is it

**Comment by dries007** [comment]
If you can't specify what block it you are looking at, i'm going to have a hard time fixing it. But I'll try.

**Comment by sanyashvets** [comment]
Here is some console spam:
[09:04:03] [Server thread/WARN]: Some error while sending over inventory, no hologram for you :(
[09:04:03] [Server thread/WARN]: Please make an issue on github if this happens.
[09:04:03] [Server thread/WARN]: java.lang.NullPointerException
[09:04:03] [Server thread/WARN]: Some error while sending over inventory, no hologram for you :(
[09:04:03] [Server thread/WARN]: Please make an issue on github if this happens.
[09:04:03] [Server thread/WARN]: java.lang.NullPointerException


I`ll try to find inventory too after update to latest version. Now I`m using 108 build

**Comment by dries007** [comment]
Yes, please make sure it happens with updated versions!

**Comment by sanyashvets** [comment]
Ok, I`ll  check it in a few hours!

**Comment by sanyashvets** [comment]
I didn`t found item with error. 
Problem repeats after updating to latest (109) build

**Comment by trismegistis** [comment]
Hi I also receive this error spam, I'm sure its a user on my server. Do I need this installed Server-Side? Maybe thats the problem?

**Comment by dries007** [comment]
Yes, the mod needs to be installed on both sides for it to work.
The problem is that I need to know what they where looking at, so I can make code to deal with it.

**Comment by sanyashvets** [comment]
This mod installed both client and server. Console still spaming errors)

**Comment by dries007** [comment]
Can you post some of the console spam? The mod has been updated since the initial error report and the line numbers are no longer accurate.

**Comment by dries007** [comment]
Scratch that, I think I figured it out

**Comment by trismegistis** [comment]
Will try. Sorry I'm running a server with over 14 people online when i last
saw it, or I'd have maybe been able to get more info

**Comment by dries007** [comment]
I should have looked around better before complaining, It was a relatively new addition (the double chest code) that caused this
