### ISSUE TITLE
Client crash on startup when I:keyMode!=0

### ISSUE THREAD

**Issue by lossycrypt** [dries007/HoloInventory#19]
As stated above the client won't even get to the main menu before crashing if i set keyMode to 1 or 2.

```
[04:36:36] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 15/10/18 4:36
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.dries007.holoInventory.client.KeyManager.input(KeyManager.java:87)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_186_KeyManager_input_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2275726920 bytes (2170 MB) / 3234332672 bytes (3084 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:MaxPermSize=2G -XX:ReservedCodeCacheSize=1G -Xmx8G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJA	OpenComputers|Core{1.5.18.36} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJA	IC2{2.2.782-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.782-experimental.jar) 
	UCHIJA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9b.jar) 
	UCHIJA	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V9b.jar) 
	UCHIJA	ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V9b.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCHIJA	HoloInventory{1.9.1.122} [HoloInventory] (HoloInventory-1.7.10-1.9.1.122.jar) 
	UCHIJA	hyperioncraft{1.7.10-0.2.3a} [HyperionCraft] (hyperioncraft-1.7.10-0.2.3a.jar) 
	UCHIJA	OpenComputers{1.5.18.36} [OpenComputers] (OpenComputers-MC1.7.10-1.5.18.36-universal.jar) 
	UCHIJA	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.1.jar) 
	UCHIJA	JAKJ_RedstoneInMotion{2.8.7} [Remain In Motion] (RemainInMotion-2.8.7.jar) 
	UCHIJA	SGCraft{1.9.3} [Greg's SG Craft] (SGCraft-1.9.3-mc1.7.10.jar) 
	UCHIJA	teleporter{1.0.2} [Vanilla-Inspired Teleporters] (VanillaTeleporter-1.7.10-1.0.2.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.60' Renderer: 'GeForce GT 650M/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GT 650M/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[04:36:36] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# E:\minecraft\bergwerk2.0\instances\bergwerk2\minecraft\crash-reports\crash-2015-10-18_04.36.36-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by lossycrypt** [comment]
Seems to be caused by having I:keyCode=-100 (first mouse button for me).
If i set keyCode to 0 i can start with keyMode 1, but if i then change the hotkey in the in-game setting to mouse button 1 again it instacrashes. (Obviously i'm not actually trying to bind it to mouse1, i just accidentially clicked that.)
